server:
  port: 8080
spring:
  application:
    name: Sparkfolio_Back

  devtools:
    livereload:
      enabled: true #?? ??
    restart:
      enabled: true #?? ??

  thymeleaf:
    cache: false #?? ??

  #MYSQL ??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sparkfolio
    username: root
    password: ksh1230*

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true  # ????? ???? ??
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  security:
    user:
      name: test
      password: 1234
  servlet:
    multipart:
      enabled: true  # 멀티파트 업로드 활성화
      max-request-size: 10MB
      max-file-size: 10MB
    # 파일 업로드 설정
    file:
      saveDir: C:/shop/item #서버의 내부에서 사용할 경로(파일 저장)
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace


