server:
  port: 8080

spring:
  application:
    name: Sparkfolio_Back

  devtools:
    livereload:
      enabled: true #?? ??
    restart:
      enabled: true #?? ??

  thymeleaf:
    cache: false #?? ??

  #MYSQL ??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sparkfolio
    username: root
    password: ksh1230*

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true  # ????? ???? ??
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  security:
    user:
      name: test
      password: 1234
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace